# Generated by Django 4.0.1 on 2022-01-06 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('spreadsheet_row', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalcost', models.DecimalField(decimal_places=2, max_digits=100)),
                ('time_occured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.date')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('column', models.CharField(max_length=3)),
                ('max_quota', models.IntegerField()),
                ('purchased_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.transaction')),
            ],
        ),
    ]
